apiVersion: apps/v1
kind: Deployment
metadata:
    name: webserver
spec:
    minReadySeconds: 5
    selector:
        matchLabels:
            app: webserver
    replicas: 2
    template:
        metadata:
            labels:
                app: 'webserver'
        spec:
            containers:
            - name: webserver
              image: nginx
