apiVersion: v1
kind: Service
metadata:
    name: 'webserver'
spec:
    selector:
        app: webserver
    ports:
        - name: http
          port: 80
          nodePort: 30080

    type: NodePort